FROM debian

RUN apt-get update && \
    apt-get -y install \
        git \
        g++ \
        cmake \
        make \
        python3 \
        python3-pip \
        perl \
        tar \
        gzip \
        libgtest-dev \
        libzmq3-dev \
    && \
    apt-get clean
